### ISSUE TITLE
Can't access RGB triplet with blockIndices

### ISSUE THREAD

**Issue by thibauts** [scijs/cwise#6] opened 2015-07-06 16:05 UTC
I'm trying to process an image and need to access the full RGB triplet on each loop.

```javascript
var myop = cwise({
  args: [{ blockIndices: -1 }, 'scalar'],
  body: function(rgb, s) {
      console.log(rgb[0], rgb[1], rgb[2]); // <= this works
      console.log(rgb); // <= this doesn't
    }
  }
});
```

The error I get is `Uncaught ReferenceError: _inline_1_arg0_ is not defined`.

ping @jaspervdg

**Comment by rreusser** [comment] 2015-07-06 16:21
I believe the issue is that `rgb` isn't a list but is just convenient notation that gets parsed and rewritten by cwise to pretend as if it were. Javascript subarrays don't handle list items with non-unit stride, so I think the short answer is that if you need rgb as list in cwise, you'll actually have to write `[rgb[0],rgb[1],rgb[2]]`.

More specifically, `rgb[0]`, `rgb[1]`, and `rgb[1]` are getting parsed and rewritten and passed as variables _inline_1_arg0_, so that the actual code that's getting executed is something more like:

```javascript
console.log(_inline_1_arg0_, _inline_1_arg1_, _inline_1_arg2_);
```

**Comment by rreusser** [comment] 2015-07-06 16:37
To rephrase more to the point: There's no native javascript construct (yet?) for slicing and passing around the components in the way you're describing. If what you're trying to do is overwrite the components via a function (just guessing), then I think you'll either have to inline the function into `body` and set them (e.g. `rgb[0] = 128` and then let cwise take it from there) or you'll have to return the answer from a function and then reassign them, which would work but is maybe not optimal, depending on what the js engine actually does with this, e.g.:

```javascript
body: function(rgb) {
  var rgbDark = darken(rgb[0], rgb[1], rgb[2])
  rgb[0] = rgbDark[0]
  rgb[1] = rgbDark[1]
  rgb[2] = rgbDark[2]
}
```

**Comment by thibauts** [comment] 2015-07-06 21:44
That's what I ended up doing. Given how cwise works what you say makes perfect sense yet it's counterintuitive when  you don't know the internals.

The issue should probably be closed. Not sure ...

**Comment by jaspervdg** [comment] 2015-07-08 08:25
At some point it could be nice to rewrite cwise to be much more flexible, but for now I think this issue can be closed (in the sense that for the moment it's expected behaviour).

**Closed by jaspervdg** 2015-07-08 08:25 UTC

**Comment by rikkertkoppes** [comment] 2016-02-02 12:29
Working on scanning a greyscale image (2D ndarray) line by line while running into the above issue.

Goal is to find lines that satisfy a pattern and outputting the indices of these lines. Idea was to get a line as array inside the body and checking for the pattern. However, this obviously fails since we don't have an actual array.

What would be the correct way to do this? I can imagine this is a common use-case

**Comment by jaspervdg** [comment] 2016-02-02 13:45
Can you be more specific about what you mean by "this obviously fails"? Apart from passing the argument to something else as an array and some other "advanced" use cases there is actually a surprising amount of stuff that does work. So what did you try and in what way did it fail?

**Comment by rreusser** [comment] 2016-02-02 14:18
Cwise may or may not be a good fit for your problem. It's great for component-wise operations, but might not be appropriate for analyzing slices along a whole axis. You may wish to [work with slices](https://github.com/scijs/ndarray#arraypickp0-p1-) instead, e.g.:

```javascript
var ndarray = require('ndarray')

var A = ndarray([1, 2, 3, 4, 5, 6], [3, 2])

// Output the matrix row by row:
for(var j = 0; j < A.shape[0]; j++) {
  console.log('row ' + j + ': ' + show(A.pick(j, null)))
}
// row 0:    1.000    2.000
// row 1:    3.000    4.000
// row 2:    5.000    6.000
```

Each slice is an ndarray with identically the same internal data array as `A`; In other words, you could write a plain javascript loop that iterates over slices and processes each slice individually. If you modify a slice, the original array is modified.

If it helps, I've tried to collect a lot of basic operations [here](https://github.com/scijs/scijs-ndarray-for-matlab-users). Cwise is great for a lot of them, but not all of them.

**Comment by jaspervdg** [comment] 2016-02-02 15:33
Actually, while I agree cwise is definitely not always be the best fit, it should allow for looping over a slice. In particular, the following works just fine:
```javascript
"use strict"
var ndarray = require('ndarray')
var show = require('ndarray-show')
var cwise = require('./cwise')

var a = ndarray([1, 2, 3, 4, 5, 6], [2, 3])
var b = ndarray([0, 0], [2])

var op = cwise({
	args: ['array', {blockIndices: -1}, 'scalar'],
	body: function(sum, row, n) {
		sum = 0
		for(var i=0; i<n; i++) {
			sum += row[i]
		}
	}
})

console.log(show(a))
op(b, a, a.shape[1])
console.log(show(b))
```

**Comment by rreusser** [comment] 2016-02-02 15:36
Interesting. I need to do work at the moment, but I'm very curious to see what the expanded iteration looks like. I assumed blockIndices was great for small rgb-type dimensions but that it would fall apart for large dimensions. I'll check this in a bit.

**Comment by rikkertkoppes** [comment] 2016-02-05 10:42
I was trying Array.forEach, which was the thing that obviously failed. I assumed iterating over the indices would also not work, but indeed it works just fine.

Goal was to find 1:1:3:1:1 patterns on a line to be able to detect QR corner markers. Which works.
